
name: Release

on:
  release:
    types:
      - released

jobs:
  release:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 7

      - name: Set up Maven settings.xml to access Sonatype Nexus
        run: |
          echo '
            <settings xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.0.0 http://maven.apache.org/xsd/settings-1.0.0.xsd">
              <servers>
                <server>
                  <id>ossrh</id>
                  <username>${{ secrets.OSSRH_USER }}</username>
                  <password>${{ secrets.OSSRH_PASS }}</password>
                  <passphrase>${{ secrets.OSSRH_SIGNING_PASSWORD }}</passphrase>
                </server>
              </servers>
            </settings>
          ' > ~/.m2/settings.xml

      - name: Set up GPG keys
        run: |
          mkdir .gpg
          echo $(echo '${{ secrets.OSSRH_SIGNING_SECRET_KEY_RING_BASE64 }}' | base64 --decode) > .gpg/private_key.gpg
          gpg --import .gpg/private_key.gpg
          rm -rf .gpg

      - name: Release
        run: bash mvnw -B clean deploy -DskipTests -Prelease
